# Generated by Django 6.1 on 2026-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['activa'], name='cajas_caja_activa_70ed15_idx'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['estado'], name='cajas_caja_estado_6d09d6_idx'),
        ),
    ]