# Generated by Django 6.0.7 on 2026-08-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('GARANTIA', 'Garantía'), ('CAMBIO_PRODUCTO', 'Cambio de producto')], max_length=30),
        ),
    ]
