# Generated by Django 6.0.7 on 2026-08-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_nuevo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
