# Generated by Django 6.0.7 on 2026-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientoinventario_stock_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_defectuoso_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_defectuoso_nuevo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
