# Generated by Django 6.0.7 on 2026-08-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_movimientoinventario_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
