# Generated by Django 6.0.7 on 2026-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=30, unique=True),
        ),
    ]
