# Generated by Django 6.1 on 2026-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_productos_p_activo_31f808_idx_and_more'),
        ('variantes', '0002_variante_stock_defectuoso'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['activo'], name='variantes_v_activo_20645b_idx'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['producto', 'activo'], name='variantes_v_product_850e37_idx'),
        ),
    ]