# Generated by Django 6.0.7 on 2026-07-26 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corte_caja', '0001_initial'),
        ('metodos_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'COMPLETADA'), ('CANCELADA', 'CANCELADA'), ('DEVUELTA', 'DEVUELTA')], default='COMPLETADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('corte_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='corte_caja.cortecaja')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='metodos_pago.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['folio'], name='ventas_vent_folio_f7143d_idx'), models.Index(fields=['usuario'], name='ventas_vent_usuario_18c0be_idx'), models.Index(fields=['corte_caja'], name='ventas_vent_corte_c_ed1bee_idx'), models.Index(fields=['fecha'], name='ventas_vent_fecha_8683f5_idx'), models.Index(fields=['estado'], name='ventas_vent_estado_b0d674_idx')],
            },
        ),
    ]
