# Generated by Django 6.0.7 on 2026-07-24 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_menudeo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_mayoreo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('garantia_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='productos.producto')),
            ],
        ),
    ]
