# Generated by Django 6.0.7 on 2026-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='stock_defectuoso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
