# Generated by Django 6.1 on 2026-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activo'], name='categorias__activo_031ff3_idx'),
        ),
    ]