# Generated by Django 6.0.7 on 2026-08-11 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_caja', '0001_initial'),
        ('devoluciones', '0001_initial'),
        ('metodos_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('REEMBOLSO', 'Reembolso'), ('AJUSTE', 'Ajuste')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('corte_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='corte_caja.cortecaja')),
                ('devolucion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_caja', to='devoluciones.devolucion')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='metodos_pago.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['corte_caja'], name='corte_caja__corte_c_b6a5eb_idx'), models.Index(fields=['metodo_pago'], name='corte_caja__metodo__59e03e_idx'), models.Index(fields=['tipo'], name='corte_caja__tipo_a38c98_idx'), models.Index(fields=['fecha'], name='corte_caja__fecha_b8080c_idx')],
            },
        ),
    ]
