# Generated by Django 6.0.7 on 2026-08-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_caja', '0002_movimientocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('REEMBOLSO', 'Reembolso')], max_length=30),
        ),
    ]
