# Generated by Django 6.0.7 on 2026-08-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(0, 'superadmin'), (1, 'admin'), (2, 'empleado')], default=2),
        ),
    ]
