# Generated by Django 6.0.7 on 2026-08-25 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_venta', '0001_initial'),
        ('variantes', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('resolucion', models.CharField(blank=True, choices=[('REEMPLAZO', 'Reemplazo'), ('CAMBIO_PRODUCTO', 'Cambio de producto'), ('REPARACION', 'Reparación')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='detalle_venta.detalleventa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='variantes.variante')),
                ('variante_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias_como_nueva', to='variantes.variante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['venta'], name='garantias_g_venta_i_68ca4c_idx'), models.Index(fields=['detalle_venta'], name='garantias_g_detalle_e34f48_idx'), models.Index(fields=['variante'], name='garantias_g_variant_dce793_idx'), models.Index(fields=['estado'], name='garantias_g_estado_d9a0ca_idx')],
            },
        ),
    ]
