# Generated by Django 6.1 on 2026-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0002_alter_metodopago_nombre'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metodopago',
            index=models.Index(fields=['activo'], name='metodos_pag_activo_3be852_idx'),
        ),
    ]