# Generated by Django 6.0.7 on 2026-07-26 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('mensaje_ticket', models.TextField()),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_devolucion', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
