# Generated by Django 6.0.7 on 2026-09-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
    ]
