# Generated by Django 6.1 on 2026-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_categorias__activo_031ff3_idx'),
        ('productos', '0002_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_p_activo_31f808_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='productos_p_categor_5dba6d_idx'),
        ),
    ]