# Generated by Django 6.0.7 on 2026-08-11 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
        ('metodos_pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='metodo_pago_reembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_reembolsadas', to='metodos_pago.metodopago'),
        ),
    ]
